version: '3'

volumes:
  postgresql_data:
    driver: local

networks:
  twideo:
    driver: bridge

services:
  twideo_postgresql:
    container_name: twideo_postgresql
    image: bitnami/postgresql:15.1.0-debian-11-r13
    networks:
      - twideo
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=twideo
      - POSTGRESQL_PASSWORD=twideo
      - POSTGRESQL_DATABASE=twideo
